export const TASKS_CHANGED = 'TASKS_CHANGED';
export const EDITING_TASK_START = 'EDITING_TASK_START';
export const EDITING_TASK_CANCELLED = 'EDITING_TASK_CANCELLED';
export const EDITING_TASK_FINISHED = 'EDITING_TASK_FINISHED';